import math
from datetime import timedelta

from odoo import Command, _, api, fields, models
from odoo.exceptions import AccessError, UserError, ValidationError


class PayslipPaymentCandidateSession(models.TransientModel):
    _name = 'il.payslip.payment.candidate.session'
    _description = 'Payslip Payment Candidate Session'
    _transient_max_hours = 2

    source_payslip_id = fields.Many2one('hr.payslip', required=True, readonly=True, ondelete='cascade')
    company_id = fields.Many2one(related='source_payslip_id.company_id')
    currency_id = fields.Many2one(related='source_payslip_id.currency_id')
    editor_id = fields.Many2one('il.payroll.reconciliation.wizard', readonly=True, ondelete='cascade')
    line_ids = fields.One2many('il.payslip.payment.candidate.line', 'session_id', readonly=True)
    applied = fields.Boolean(readonly=True)

    @api.model_create_multi
    def create(self, vals_list):
        # The source is the sole client input. Candidate identities, proposal
        # defaults and accounting snapshots are generated by the server.
        sessions = super().create([{'source_payslip_id': vals.get('source_payslip_id')}
                                   for vals in vals_list])
        for session in sessions:
            editor = self.env['il.payroll.reconciliation.wizard'].create({
                'source_payslip_id': session.source_payslip_id.id, 'add_only': True,
            })
            super(PayslipPaymentCandidateSession, session).write({'editor_id': editor.id})
            session._check_session()
            remaining = max(-sum(session.source_payslip_id._il_salary_payable_lines().mapped(
                'amount_residual_currency')), 0.0)
            candidates = editor._eligible_payments(session.source_payslip_id)
            self.env['il.payslip.payment.candidate.line']._create_for_session(
                session, candidates, remaining)
        return sessions

    def write(self, vals):
        raise ValidationError(_('יש לפתוח מחדש את חלון הוספת התשלומים כדי לשנות את מקורו.'))

    def _check_session(self, lock=False):
        self.ensure_one()
        if not self.env.user.has_group('hr_payroll.group_hr_payroll_user'):
            raise AccessError(_('ניהול תשלומים מקושרים זמין למשתמשי השכר בלבד.'))
        if not self.exists():
            raise UserError(_('חלון הוספת התשלומים פג תוקף. יש לפתוח אותו מחדש מהתלוש.'))
        self.check_access('read')
        self.check_access('write')
        if self.create_uid != self.env.user:
            raise AccessError(_('חלון הוספת התשלומים שייך למשתמש אחר.'))
        if lock:
            self.env.cr.execute(
                'SELECT id FROM il_payslip_payment_candidate_session WHERE id = %s FOR UPDATE',
                [self.id])
            self.invalidate_recordset(['applied', 'create_date', 'editor_id'])
        if self.applied:
            raise UserError(_('התשלומים כבר קושרו. יש לפתוח חלון חדש להוספת תשלומים נוספים.'))
        if not self.create_date or fields.Datetime.now() >= self.create_date + timedelta(hours=2):
            raise UserError(_('חלון הוספת התשלומים פג תוקף. יש לפתוח אותו מחדש מהתלוש.'))
        if self.company_id not in self.env.companies:
            raise AccessError(_('חברת התלוש אינה בין החברות הפעילות שלך.'))
        source_id = self.env.context.get('il_payslip_id')
        if source_id is not None and source_id != self.source_payslip_id.id:
            raise ValidationError(_('חלון הוספת התשלומים אינו שייך לתלוש זה.'))
        self.source_payslip_id.check_access('read')
        if not self.editor_id.exists():
            raise UserError(_('חלון הוספת התשלומים פג תוקף. יש לפתוח אותו מחדש מהתלוש.'))

    def _apply_payments(self, payments):
        self.ensure_one()
        with self.env.cr.savepoint():
            self._check_session(lock=True)
            payments.check_access('read')
            payments.check_access('write')
            if not payments or payments != payments.exists() or payments - self.line_ids.payment_id:
                raise ValidationError(_('יש לבחור תשלומים מתוך החלון הנוכחי בלבד.'))
            lines = self.line_ids.filtered(lambda line: line.payment_id in payments)
            lines.invalidate_recordset(['amount'])
            lines = lines.filtered(lambda line: self.currency_id.compare_amounts(line.amount, 0.0) > 0)
            if not lines:
                raise ValidationError(_('יש להזין סכום חיובי להכרה לפחות באחד מהתשלומים שנבחרו.'))
            editor = self.editor_id
            partials = editor._scope_partials()
            editor._lock_records(partials.debit_move_id.payment_id | lines.payment_id,
                                 partials.credit_move_id.il_payslip_id | self.source_payslip_id)
            if editor._fingerprint() != editor.snapshot:
                raise UserError(_('הסכומים בתלוש השתנו מאז פתיחת החלון. יש לפתוח אותו מחדש.'))
            for line in lines:
                editor._check_pair(line.payment_id, self.source_payslip_id)
                if line.snapshot != line.payment_id._il_payslip_link_token(self.source_payslip_id):
                    raise UserError(_('התשלום או יתרתו השתנו מאז פתיחת החלון. יש לפתוח אותו מחדש.'))
                line._validate_amount(line.amount)
            # The existing selection/editor flow owns native reconciliation,
            # stale checks, accounting locks and atomic capacity validation.
            # It is applied directly: no second review dialog is displayed.
            selection = self.env['il.payslip.payment.selection.wizard'].create({
                'source_payslip_id': self.source_payslip_id.id, 'operation': 'add',
                'selected_payment_ids': [Command.set(lines.payment_id.ids)],
            })
            amounts = {line.payment_id.id: line.amount for line in lines}
            for row in selection.line_ids:
                row.amount = amounts[row.payment_id.id]
            result = selection.action_apply()
            super(PayslipPaymentCandidateSession, self).write({'applied': True})
            return result


class PayslipPaymentCandidateLine(models.TransientModel):
    _name = 'il.payslip.payment.candidate.line'
    _description = 'Payslip Payment Candidate Amount'
    _transient_max_hours = 2

    session_id = fields.Many2one('il.payslip.payment.candidate.session', required=True,
                                 readonly=True, ondelete='cascade', index=True)
    payment_id = fields.Many2one('account.payment', required=True, readonly=True, ondelete='cascade')
    currency_id = fields.Many2one(related='session_id.currency_id')
    amount = fields.Monetary(string='סכום להכרה', required=True)
    available_amount = fields.Monetary(readonly=True)
    snapshot = fields.Char(required=True, readonly=True)

    @api.model_create_multi
    def create(self, vals_list):
        raise ValidationError(_('יש לבחור תשלומים מתוך חלון הוספת התשלומים.'))

    @api.model
    def _create_for_session(self, session, payments, remaining):
        session._check_session()
        payments.check_access('read')
        rows = []
        for payment in payments:
            available = payment.il_recognition_available_amount
            rows.append({
                'session_id': session.id, 'payment_id': payment.id,
                'amount': min(available, remaining), 'available_amount': available,
                'snapshot': payment._il_payslip_link_token(session.source_payslip_id),
            })
        return super().create(rows)

    def _validate_amount(self, value):
        self.ensure_one()
        try:
            amount = float(value)
        except (TypeError, ValueError):
            raise ValidationError(_('יש להזין סכום תקין להכרה.')) from None
        if not math.isfinite(amount) or self.currency_id.compare_amounts(amount, 0.0) < 0:
            raise ValidationError(_('הסכום להכרה חייב להיות אפס או חיובי.'))
        if self.currency_id.compare_amounts(amount, self.available_amount) > 0:
            raise ValidationError(_('הסכום להכרה גבוה מהיתרה הזמינה של התשלום.'))
        return self.currency_id.round(amount)

    def write(self, vals):
        if set(vals) != {'amount'}:
            raise ValidationError(_('בחלון זה ניתן לשנות רק את הסכום להכרה.'))
        with self.env.cr.savepoint():
            for line in self:
                line.session_id._check_session(lock=True)
                line.payment_id.check_access('write')
                super(PayslipPaymentCandidateLine, line).write({
                    'amount': line._validate_amount(vals['amount']),
                })
            self.payment_id.invalidate_recordset(['il_payslip_candidate_amount'])
        return True


class AccountPayment(models.Model):
    _inherit = 'account.payment'

    il_payslip_candidate_amount = fields.Monetary(
        string='סכום להכרה', currency_field='currency_id',
        compute='_compute_il_payslip_candidate_amount', inverse='_inverse_il_payslip_candidate_amount')

    @api.model
    def _il_candidate_session(self):
        session_id = self.env.context.get('il_payslip_candidate_session_id')
        if not isinstance(session_id, int) or isinstance(session_id, bool) or session_id <= 0:
            raise ValidationError(_('יש לפתוח את הוספת התשלומים מתוך תלוש.'))
        session = self.env['il.payslip.payment.candidate.session'].browse(session_id)
        session._check_session()
        return session

    @api.depends_context('il_payslip_candidate_session_id', 'il_payslip_id', 'uid')
    def _compute_il_payslip_candidate_amount(self):
        amounts = {}
        if self.env.context.get('il_payslip_candidate_session_id'):
            session = self._il_candidate_session()
            amounts = {line.payment_id.id: line.amount for line in session.line_ids}
        for payment in self:
            payment.il_payslip_candidate_amount = amounts.get(payment._origin.id, 0.0)

    def _inverse_il_payslip_candidate_amount(self):
        for payment, amount in [(payment, payment.il_payslip_candidate_amount) for payment in self]:
            payment._il_save_candidate_amount(amount)

    def _il_save_candidate_amount(self, amount):
        self.ensure_one()
        self.check_access('write')
        session = self._il_candidate_session()
        line = session.line_ids.filtered(lambda candidate: candidate.payment_id == self)
        if len(line) != 1:
            raise ValidationError(_('התשלום אינו מופיע בחלון הוספת התשלומים הנוכחי.'))
        line.write({'amount': amount})

    def write(self, vals):
        if 'il_payslip_candidate_amount' in vals:
            if set(vals) != {'il_payslip_candidate_amount'}:
                raise ValidationError(_('בחלון הוספת התשלומים ניתן לשנות רק את הסכום להכרה.'))
            with self.env.cr.savepoint():
                for payment in self:
                    payment._il_save_candidate_amount(vals['il_payslip_candidate_amount'])
            # Do not write the financial payment even its write_date/chatter.
            return True
        return super().write(vals)

    def action_il_add_payslip_payment(self):
        action = super().action_il_add_payslip_payment()
        session = self.env['il.payslip.payment.candidate.session'].create({
            'source_payslip_id': self._il_context_payslip().id,
        })
        action['domain'] = [('id', 'in', session.line_ids.payment_id.ids)]
        action['target'] = 'new'
        action['context'] = dict(action['context'], edit=True, dialog_size='extra-large',
                                 il_payslip_candidate_session_id=session.id)
        return action

    def action_il_select_payslip_payments(self):
        return self._il_candidate_session()._apply_payments(self)
