from . import hr_employee
from . import hr_version
from . import hr_payslip_input_type
from . import hr_salary_attachment
from . import hr_payslip_input
from . import hr_payslip
from . import account_payment
from . import account_payment_payslip_allocation
from . import hr_employee_payment_cycle_setting
from . import hr_payroll_cycle
