from odoo import fields, models
from odoo.tools.float_utils import float_compare


class HrAttendanceOvertimeLine(models.Model):
    _inherit = 'hr.attendance.overtime.line'

    mdl_auto_approval_hours = fields.Float(
        string='Automatically Calculated Approval Hours', readonly=True, copy=False,
        help='Original rounded approval hours generated by the whole-shift rule. '
             'Used to distinguish automatic rounding from a later manual change.',
    )

    def _mdl_has_manual_duration_override(self):
        self.ensure_one()
        baseline = self.mdl_auto_approval_hours if self.mdl_auto_approval_hours > 0 else self.duration
        return float_compare(self.manual_duration, baseline, precision_digits=4) != 0
